# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_bord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='japan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message_bord',
            name='new_message',
            field=models.TextField(default='japan', max_length=200),
            preserve_default=False,
        ),
    ]
